language: node_js
node_js:
  - "lts/*"

cache:
  yarn: true
  directories:
    - "node_modules"

# use latest yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

# fix upath incompatibility
install: yarn --ignore-engines

# GitHub Pages deploy
before_deploy:
  - npm run predeploy

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    keep-history: true
    on:
      branch: master
    local-dir: demo
  - provider: npm
    skip-cleanup: true
    email: "leishenghao@126.com"
    api_key: $NPM_AUTH_TOKEN
    on:
      tags: true